{
 "title": "CRM ApiHub Observability",
 "tags": [
  "crm",
  "apihub"
 ],
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{job=\"nyx_crm_apihub\"}[1m])",
     "legendFormat": "{{code}} - {{method}} - {{controller}}"
    }
   ]
  },
  {
   "title": "API Hub Memory & CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_working_set_bytes{job=\"nyx_crm_apihub\"}",
     "legendFormat": "Memory (Working Set)"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"nyx_crm_apihub\"}[1m])",
     "legendFormat": "CPU Usage (Rate)"
    }
   ]
  },
  {
   "title": "Live Logs - CRM ApiHub",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"nyx_crm_apihub\"} |= ``"
    }
   ]
  }
 ]
}